Repository green-code-initiative/ecoCode-python-test-project, pull requests merged in 2023-05, with the labels that each got.

#2 [EC10-Python] Add detection of unoptimized vector images
  src/avoidUnoptimizedVectorImages.py
Labels: :card_file_box: rule, 🏆 challenge 🏆

#1 feat: add tests for rule PYT404
  src/AvoidListComprehensionInIterations.py
Labels: 👀 👀 review done 👀 👀, :card_file_box: rule, 🏆 challenge 🏆

#3 [Rule 203] add test files
  src/avoidGettersAndSetters.py
  src/avoidTryCatchFinallyCheck.py
  src/detectUnoptimizedImageFormat.py
  src/detectUnoptimizedImageFormatCompliant.py
  src/noFunctionCallWhenDeclaringForLoop.py
Labels: :card_file_box: rule, 🏆 challenge 🏆

#4 EC66-PYTHON - Avoiding the use of quotation marks
  src/avoidDoubleQuoteCheck.py
Labels: enhancement, good first issue, :card_file_box: rule
